### ISSUE TITLE
Is there a way to change the icon and the work vlc media player?

### ISSUE THREAD

**Issue by Bozic421** [Pigpog/vlc-discord-rpc#51]
Is there a way to change the icon and the word 'vlc media player'?
I don't see a option to change the icon in the config file is it possible? 
![image](https://user-images.githubusercontent.com/81369341/114494153-7b432900-9c39-11eb-8a7b-2994e4b01f64.png)

**Comment by Pigpog** [comment]
Commit cd522d069a9bd9985b920fe0baec603c76e01c27 adds the ability to change the icon that's used. This is limited to the images found in the Discord application. To change the application ID used, you can change the id field in the config.
To create your own application, go to [Discord Developer Portal](https://discordapp.com/developers). Create the application and add rich presence to it. Then upload assets named "play", "paused", "stopped", and whatever you want for the large cone icon.

**Comment by Bozic421** [comment]
That works but I can't figure out a way to change the words "vlc media player" over it.

**Comment by Pigpog** [comment]
That text is associated with the application ID. You will need to create your own application to change it, using the process described above.

**Comment by Bozic421** [comment]
Yas that worked last question, So when I start the npm it displays the name of the title bar above the player 
![image](https://user-images.githubusercontent.com/81369341/116654198-4f000a00-a9a6-11eb-8e1f-4f6a5c70f2e3.png) which is 
![image](https://user-images.githubusercontent.com/81369341/116654219-5a533580-a9a6-11eb-8736-7f32c745e5fb.png) is there a way to make it show the file name instead ?
![image](https://user-images.githubusercontent.com/81369341/116654285-748d1380-a9a6-11eb-83a0-5d28a983d9da.png)

**Comment by Pigpog** [comment]
The data displayed in the rich presence is never taken from the title bar. It uses the http interface of vlc to obtain all available data from VLC in JSON format. The most relevant data available for the media is what gets shown (song name, episode number, etc), with the last resort being filename.

You can investigate this data yourself by manually setting a password in config.js if you haven't already, then open a browser to [http://127.0.0.1:8080/requests/status.json](http://127.0.0.1:8080/requests/status.json). When asked for a username and password, leave username blank and use the password you set.

If you could reproduce this issue and send a copy of the data from that link here, I could tell you exactly why it is saying Avidemux. I have a suspicion that this exact issue might be largely unsolvable, because clearly the word "Avidemux" is pretending to be useful information.

**Comment by Bozic421** [comment]
Thank you .
