### ISSUE TITLE
How can I just show the video file name instead of the extracted metadata info in status?

### ISSUE THREAD

**Issue by eXil3d** [Pigpog/vlc-discord-rpc#55]
I want to just show the video file name instead of show name and season number extracted from the metadata in my discord status. How can I do it by editing the format file?

**Comment by Pigpog** [comment]
Simply delete lines 26 - 60, so from the comment `if video` to the closing curly brace after `output.state = status.state`.
Then change line 20 to say `details: meta.filename,` instead of having `meta.title || meta.filename`.

This will remove the second line of info altogether, and show the filename even when title metadata is available.

**Comment by Pigpog** [comment]
no problem, glad it worked
