### ISSUE TITLE
VLC is classified as a game instead of music

### ISSUE THREAD

**Issue by Nixinova** [Pigpog/vlc-discord-rpc#58]
This program leads to VLC being classified as a game in Discord, saying "Playing X", instead of being labelled "Listening to X" like e.g. Spotify. Is it possible for this classification to be changed or can it only classify as "Listening to" when it's an official connection?

Comparison:
![image](https://user-images.githubusercontent.com/42429413/139771668-f0c69164-1514-4cca-952e-b4cec795eddd.png) - "Listening To" (good)
![image](https://user-images.githubusercontent.com/42429413/139771728-da55b700-58d8-4e15-ad8a-9026ab3e21b2.png) - "Playing A Game" (bad)

**Comment by Pigpog** [comment]
It is not possible to specify "Listening To" as a rich presence. Spotify and Discord have a special agreement that allows their rich presence to be a lot more advanced (the album art is an external asset, they get a timeline, Listening To, and an additional line of text).

I tried years ago to get it to be Listening To, and it turns out that if you use a self-bot you can get Listening To and even the unseen "Watching" status messages, but only for basic presences (like "Listening to VLC" with no other info), not rich presences.

So unless something has changed since then, it's not an option for anyone at the moment.

**Comment by Nixinova** [comment]
Alright, thanks for the quick response.
